### ISSUE TITLE
Idle time from resource pool does not get properly translated to k8s

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-data-services#654]
btw, it seems that the idle / hibernation thresholds are not properly being accounted for in v2 sessions (I guess this is probably a data service bug??)

A session from a resource pool with a 2h max idle time has
```
  culling:
    maxAge: 0s
    maxFailedDuration: 0s
    maxHibernatedDuration: 336h15m0s
    maxIdleDuration: 12h15m0s
    maxStartingDuration: 0s
```
