### ISSUE TITLE
Image builds: add labels and annotations to build runs

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-data-services#671]
Suggestion:

```yaml
labels:
  renku.io/safe-username: ""
annotations:
  renku.io/build_id: ""
  renku.io/environment_id: ""
  renku.io/launcher_id: ""
  renku.io/project_id: ""
```
